blog/urls.py
from django.conf.urls import url
from django.views.generic import TemplateView
from django.contrib.sitemaps import GenericSitemap
from django.contrib.sitemaps.views import sitemap
from blog.views import *
from blog.feed import LatestPosts

info_dict = {
    'queryset': Post.objects.all(),
    'date_field': 'modified',
}

# Removed url pattern for `slug` to `[\w\-]+` and not `\S+`
# Because it will getting error 404 if use for '/' (homepage) and '/<slug>' (page/else)
# But, makesure the `url page` placed at the bottom from other urls.
# Example:
#   good: r'^(?P<slug>[\w\-]+)/$'
#   bad: r'^(?P<slug>\S+)/$'
# thanks to: http://stackoverflow.com/a/30271379/6396981

urlpatterns = [
    # Handler for Maintenance mode.
    # url(r'^$', TemplateView.as_view(template_name='maintenance.html', content_type='text/html')),

    url(r'^$', HomepageView.as_view(), name='homepage'),
    url(r'^blog/(?P<slug>[\w\-]+)/$', DetailPostView.as_view(), name='detail_post_page'),
    url(r'^search/$', SearchPostsView.as_view(), name='search_posts_page'),
    url(r'^author/(?P<username>[\w\-]+)/$', AuthorPostsView.as_view(), name='author_posts_page'),
    url(r'^tag/(?P<slug>[\w\-]+)/$', TagPostsView.as_view(), name='tag_posts_page'),

    url(r'^feed/$', LatestPosts(), name="feed"),
    url(r'^sitemap\.xml$', sitemap, {'sitemaps': {'blog': GenericSitemap(
        info_dict, priority=0.6)}}, name='django.contrib.sitemaps.views.sitemap'),
    url(r'^robots\.txt/$', TemplateView.as_view(template_name='robots.txt', content_type='text/plain')),

    url(r'^sitemap/$', SitemapView.as_view(), name='sitemap_page'),
    url(r'^contact/$', ContactView.as_view(), name='contact_page'),
    url(r'^trending/$', TrendingPostsView.as_view(), name='trending_posts_page'),
    url(r'^(?P<slug>[\w\-]+)/$', DetailPageView.as_view(), name='detail_page'),
]

blogproject/urls.py
from django.conf import settings
from django.contrib import admin
from django.conf.urls import include, url
from django.conf.urls.static import static

from django.conf.urls import (
    handler400, handler403, handler404, handler500
)
handler400 = 'blog.views.handler400'
handler403 = 'blog.views.handler403'
handler404 = 'blog.views.handler404'
handler500 = 'blog.views.handler500'

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^redactor/', include('redactor.urls')),
    url(r'^', include('blog.urls')),
	url(r'', include('comments.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

comments/urls.py
from django.conf.urls import url

from . import views

app_name = 'comments'
urlpatterns = [
    url(r'^comment/post/(?P<post_pk>[0-9]+)/$', views.post_comment, name='post_comment'),
]

comments/models.py
from django.db import models
from django.utils.six import python_2_unicode_compatible


# python_2_unicode_compatible 装饰器用于兼容 Python2
@python_2_unicode_compatible
class Comment(models.Model):
    name = models.CharField(max_length=100)
    email = models.EmailField(max_length=255)
    url = models.URLField(blank=True)
    text = models.TextField()
    created_time = models.DateTimeField(auto_now_add=True)

    post = models.ForeignKey('blog.Post')

    def __str__(self):
        return self.text[:20]

blog/forms.py
from django import forms
from nocaptcha_recaptcha.fields import NoReCaptchaField


class ContactForm(forms.Form):
    cst = {
        'class': 'form-control cst__radius',
        'required': 'required'
    }
    email = forms.EmailField(
        required=True,
        widget=forms.TextInput(attrs=cst)
    )
    subject = forms.CharField(
        required=True,
        widget=forms.TextInput(attrs=cst)
    )
    message = forms.CharField(
        required=True,
        widget=forms.Textarea(attrs=cst)
    )
    captcha = NoReCaptchaField()

blog/views.py
import time
import datetime
import socket
import json

from django.views import generic
from django.http import HttpResponse
from django.shortcuts import (render, render_to_response, redirect, get_object_or_404)
from django.core.mail import (send_mail, BadHeaderError)
from django.core.exceptions import ObjectDoesNotExist
from django.template import RequestContext
from django.conf import settings
from django.db.models import (Q, Count)

from blog.models import *
from blog.forms import ContactForm
from blog.utils.paginator import GenericPaginator

from comments.forms import CommentForm


def handler400(request):
    response = render_to_response('error_page.html', {'title': '400 Bad Request', 'message': '400'},
                                  context_instance=RequestContext(request))
    response.status_code = 400
    return response


def handler403(request):
    response = render_to_response('error_page.html', {'title': '403 Permission Denied', 'message': '403'},
                                  context_instance=RequestContext(request))
    response.status_code = 403
    return response


def handler404(request):
    response = render_to_response('error_page.html', {'title': '404 Not Found', 'message': '404'},
                                  context_instance=RequestContext(request))
    response.status_code = 404
    return response


def handler500(request):
    response = render_to_response('error_page.html', {'title': '500 Server Error', 'message': '500'},
                                  context_instance=RequestContext(request))
    response.status_code = 500
    return response


class HomepageView(generic.ListView):
    queryset = Post.objects.published()
    template_name = 'blog/blog_home.html'
    paginate_by = 10

    def get_context_data(self, **kwargs):
        context_data = super(HomepageView, self).get_context_data(**kwargs)
        context_data['page_range'] = GenericPaginator(
            self.queryset,
            self.paginate_by,
            self.request.GET.get('page')
        ).get_page_range()
        return context_data


class DetailPostView(generic.DetailView):
    model = Post
    template_name = 'blog/blog_detail.html'

    def get_client_ip(self):
        ip = self.request.META.get("HTTP_X_FORWARDED_FOR", None)
        if ip:
            ip = ip.split(", ")[0]
        else:
            ip = self.request.META.get("REMOTE_ADDR", "")
        return ip

    def visitorCounter(self):
        try:
            Visitor.objects.get(
                post=self.object,
                ip=self.request.META['REMOTE_ADDR']
            )
        except ObjectDoesNotExist:
            dns = str(socket.getfqdn(
                self.request.META['REMOTE_ADDR']
            )).split('.')[-1]
            try:
                # trying for localhost: str(dns) == 'localhost',
                # trying for production: int(dns)
                if str(dns) == 'localhost':
                    visitor = Visitor(
                        post=self.object,
                        ip=self.request.META['REMOTE_ADDR']
                    )
                    visitor.save()
                else:
                    pass
            except ValueError:
                pass
        return Visitor.objects.filter(post=self.object).count()

    def dispatch(self, request, *args, **kwargs):
        obj = self.get_object()
        if obj.publish == False:
            if request.user.is_anonymous() or \
                    request.user != obj.author.user:
                return redirect('homepage')
            else:
                return super(DetailPostView, self).dispatch(
                    request, *args, **kwargs
                )
        elif request.GET.get('format') == 'json':
            get_cover = lambda obj: None if obj.cover == None \
                or obj.cover == '' \
                else 'https://{0}{1}{2}'.format(
                    request.get_host(),
                    settings.MEDIA_URL,
                    obj.cover
                )
            data = dict(
                title=obj.title,
                url='https://{0}/blog/{1}'.format(
                    request.get_host(),
                    obj.slug
                ),
                cover=get_cover(obj),
                author=obj.author.user.username,
                created=str(obj.created)[:19],
                modified=str(obj.modified)[:19],
                tags=[
                    {'title': t.title, 'slug': t.slug}
                    for t in obj.tags.all()
                ],
                description=obj.description,
                visitors=obj.total_visitors
            )
            return HttpResponse(
                json.dumps(data),
                content_type='application/json'
            )
        else:
            return super(DetailPostView, self).dispatch(
                request, *args, **kwargs
            )

    def get_context_data(self, **kwargs):
        context_data = super(DetailPostView, self).get_context_data(**kwargs)
        related_posts = Post.objects.filter(
            tags__in=list(self.object.tags.all())
        ).exclude(id=self.object.id).distinct()
        context_data['related_posts'] = related_posts[:5]  # limit for post
        context_data['get_client_ip'] = self.get_client_ip()
        context_data['visitor_counter'] = self.visitorCounter()
        return context_data


class SearchPostsView(generic.ListView):
    template_name = 'blog/blog_search.html'
    paginate_by = 10

    def get_queryset(self):
        self.query = self.request.GET.get('q')
        try:
            search_posts = Post.objects.published().filter(
                Q(title__icontains=self.query) |
                Q(description__icontains=self.query) |
                Q(keywords__icontains=self.query) |
                Q(meta_description__icontains=self.query)
            ).order_by('-created').order_by('-id')
            return search_posts
        except:
            return Post.objects.published()

    def get_context_data(self, **kwargs):
        context_data = super(SearchPostsView, self).get_context_data(**kwargs)
        context_data['query'] = self.query
        context_data['page_range'] = GenericPaginator(
            self.get_queryset(),
            self.paginate_by,
            self.request.GET.get('page')
        ).get_page_range()
        return context_data


class AuthorPostsView(generic.ListView):
    template_name = 'blog/blog_posts_author.html'
    paginate_by = 10

    def get_queryset(self):
        username = self.kwargs['username']
        self.author = get_object_or_404(Author, user__username=username)
        posts_author = Post.objects.published().filter(
            author=self.author
        ).order_by('-created').order_by('-id')
        return posts_author

    def get_context_data(self, **kwargs):
        context_data = super(AuthorPostsView, self).get_context_data(**kwargs)
        context_data['author'] = self.author
        context_data['page_range'] = GenericPaginator(
            self.get_queryset(),
            self.paginate_by,
            self.request.GET.get('page')
        ).get_page_range()
        return context_data


class TagPostsView(generic.ListView):
    template_name = 'blog/blog_posts_tag.html'
    paginate_by = 10

    def get_queryset(self):
        slug = self.kwargs['slug']
        self.tag = get_object_or_404(Tag, slug=slug)
        results_filter = Post.objects.published().filter(
            tags=self.tag
        ).order_by('-created').order_by('-id')
        return results_filter

    def get_context_data(self, **kwargs):
        context_data = super(TagPostsView, self).get_context_data(**kwargs)
        context_data['tag'] = self.tag
        context_data['page_range'] = GenericPaginator(
            self.get_queryset(),
            self.paginate_by,
            self.request.GET.get('page')
        ).get_page_range()
        return context_data


class DetailPageView(generic.DetailView):
    model = Page
    template_name = 'blog/blog_page.html'


class SitemapView(generic.ListView):
    queryset = Post.objects.published()
    template_name = 'blog/blog_sitemap.html'
    paginate_by = 30

    def get_context_data(self, **kwargs):
        context_data = super(SitemapView, self).get_context_data(**kwargs)
        context_data['page_range'] = GenericPaginator(
            self.queryset,
            self.paginate_by,
            self.request.GET.get('page')
        ).get_page_range()
        return context_data


class ContactView(generic.TemplateView):
    template_name = 'blog/blog_contact.html'

    def post(self, request, *args, **kwargs):
        context = self.get_context_data()
        if context['form'].is_valid():
            cd = context['form'].cleaned_data
            subject = cd['subject']
            from_email = cd['email']
            message = cd['message']

            try:
                send_mail(
                    subject + " from {}".format(from_email),
                    message,
                    from_email,
                    [settings.EMAIL_HOST_USER]
                )
            except BadHeaderError:
                return HttpResponse('Invalid header found.')

            ctx = {
                'success': """Thankyou, We appreciate that you've
                taken the time to write us.
                We'll get back to you very soon.
                Please come back and see us often."""
            }
            return render(request, self.template_name, ctx)
        return super(generic.TemplateView, self).render_to_response(context)

    def get_context_data(self, **kwargs):
        context = super(ContactView, self).get_context_data(**kwargs)
        form = ContactForm(self.request.POST or None)
        context['form'] = form
        return context


class TrendingPostsView(generic.ListView):
    template_name = 'blog/blog_trending_posts.html'

    def get_queryset(self):
        posts = Post.objects.published()

blog/templates/blog/blog_contact.html
{% extends "base.html" %}
{% block title %}Contact - {{ block.super }}{% endblock %}
{% block canonical_url %}https://{{ request.get_host }}{% url 'contact_page' %}{% endblock %}

{% block content %}
<div class="post">
  <h2>联系</h2>
  {% if success %}
    <meta http-equiv="refresh" content="7;url={% url 'homepage' %}" />
    <p class="alert alert-success text-center cst__radius">{{ success }}</p>
  {% else %}
    <p><center><span style="color: #f00">请再次输入身份信息上的电子邮件</span><br />
    { 如果这种形式不能正常工作，请联系我 <a href="https://www.facebook.com/messages/agaust" target="_blank">Facebook聊天</a> }</center></p>
    <script src="https://www.google.com/recaptcha/api.js" async defer></script>
    <form action="." method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <div class="form-actions">
      <button class="btn btn-primary btn-block cst__radius" type="submit">发送</button>
    </div>
  </form>
  {% endif %}
</div>

  {% if request.GET.subject %}
  <script>
    document.getElementById("id_subject").value = "{{ request.GET.subject }}";
  </script>
  {% endif %}
{% endblock %}

blog/templates/blog/blog_detail.html
{% extends "base.html" %}
{% load staticfiles %}
{% block title %}{{ object.title }} - {{ block.super }}{% endblock %}
{% block canonical_url %}https://{{ request.get_host }}{% url 'detail_post_page' slug=object.slug %}{% endblock %}

{% block meta_seo %}
  <meta name="description" content="{% if object.meta_description %}{{ object.meta_description }}{% else %}{{ object.description|safe|striptags|truncatewords:"20" }}{% endif %}">
  <meta name="author" content="{{ object.author }}">
  <meta name="keywords" content="{% if object.keywords %}{{ object.keywords }}{% else %}{{ object.title }}{% endif %}"/>
  {% for tag in object.tags.all %}
  <meta property="article:tag" content="{{ tag.title }}" />
  {% endfor %}
  <meta property="og:locale" content="en_US" />
  <meta property="og:type" content="article" />
  <meta property="og:title" content="{{ object.title }}"/>
  <meta property="og:description" content="{% if object.meta_description %}{{ object.meta_description }}{% else %}{{ object.description|safe|striptags|truncatewords:"20" }}{% endif %}"/>
  <meta property="og:url" content="https://{{ request.get_host }}{% url 'detail_post_page' slug=object.slug %}"/>
  {% if object.cover %}
  <meta property="og:image" content="https://{{ request.get_host }}/media/{{ object.cover }}"/>
  {% endif %}
  <meta property="og:site_name" content="python.web.id" />
  <meta name="twitter:card" content="summary"/>
  <meta name="twitter:description" content="{% if object.meta_description %}{{ object.meta_description }}{% else %}{{ object.description|safe|striptags|truncatewords:"20" }}{% endif %}"/>
  {% if object.cover %}
  <meta name="twitter:image:src" content="https://{{ request.get_host }}/media/{{ object.cover }}"/>
  {% endif %}
  <meta name="twitter:title" content="{{ object.title }}"/>
  <meta name="twitter:domain" content="python.web.id"/>
  <meta name="twitter:creator" content="@agusmakmun6"/>
{% endblock %}

{% block content %}
  <div class="post" id="printable">
    <h2><a href="{% url "detail_post_page" slug=object.slug %}">{{ object.title }}</a>{% if object.publish == False %} <i class="badge">草案</i>{% endif %}</h2>
    <div class="meta">
      By: <a href="{% url 'author_posts_page' username=object.author.user.username %}" style="text-transform:uppercase">{{ object.author }}</a> &#9679;
      在 {{ object.created }} &#9679; 并修改 {{ object.modified }}<br />
      发表于：
      {% for tag in object.tags.all %}
        <a href="{% url 'tag_posts_page' slug=tag.slug %}">#{{ tag }}</a>{% if not forloop.last %}, {% endif %}
      {% empty %}非本类别
      {% endfor %}
      <br />
      你的ID地址 {{ get_client_ip }} &#9679; views: {{ visitor_counter }} times.
    </div>

    <p>
    {% if object.cover %}
    <caption align="bottom">
      <img style="width:100%" class="cover-post" src="//{{ request.get_host }}/media/{{ object.cover }}" title="{{ object.title }}" alt="{{ object.title }}"/>
    <span style="margin-left: 1px;background: #F2F4F3; padding: 0 5px; text-shadow: 1px 1px 1px #fff;">{{ object.title }}</span>
    </caption>
    {% endif %}
    </p>
    {{ object.description|safe }}
    <div class="share panel-body" id="non-printable">
	<span class="comments-link"><a href="{{ post.get_absolute_url }}#comment-area">{{ post.comment_set.count }} 评论</a></span>
                
      <span>分享到:</span>
      <a class="btn btn-sm btn-primary cst__radius" href="https://sns.qzone.qq.com/cgi-bin/qzshare/cgi_qzshare_onekey?u=https://python.web.id{% url "detail_post_page" slug=object.slug %}" target="_blank">QQ空间</a>
      <a class="btn btn-sm btn-danger cst__radius" href="http://s.jiathis.com/?webid=email&url=https://python.web.id{% url "detail_post_page" slug=object.slug %}" target="_blank">邮箱·</a>
      <a class="btn btn-sm btn-info cst__radius" href="http://service.weibo.com/share/share.php?url=https://python.web.id{% url "detail_post_page" slug=object.slug %}" target="_blank">新浪微博</a>
      <a class="btn btn-sm btn-success cst__radius" href="javascript:window.print()">打印</a>
    </div>

    <style type="text/css" media="print">
     @media print {
       #non-printable, .ip-client { display: none; }
       #printable { display: block; width: 100%;height: 100%;}
       a[href]::after {content: "";} /*content: " (" attr(href) ")"*/
     }
    </style>

    <div class="panel panel-default" id="non-printable">
    <div class="panel-heading">作者</div>
      <div class="panel-body">
        <div class="media">
          <div class="media-left media-middle" style="float: left;margin-right: 10px;">
            <a href="{% url 'author_posts_page' username=object.author.user.username %}">
              <img class="media-object" alt="{{ object.author }}" title="{{ object.author }}" src="{% if object.author.avatar %}/media/{{ object.author.avatar }}{% else %}/static/assets/icons/avatar.jpeg{% endif %}" style="width: 64px; height: 64px;">
            </a>
          </div>
          <div class="media-body">
            <h4 class="media-heading">{{ object.author }}</h4>
            {{ object.author.about|safe }}<br />
              网址: <a href="{{ object.author.website }}" target="_blank">{{ object.author.website }}</a>
          </div>
        </div>
      </div>
    </div>
	

    <div class="panel panel-default related" id="non-printable">
      <div class="panel-heading">
        <h3 class="panel-title">相关文章</h3>
      </div>
        <ul class="list-group">
          {% for post in related_posts %}
            <li class="list-group-item"><a href="{% url "detail_post_page" slug=post.slug %}">{{ post.title }}</a> - <i>{{ post.created }}</i></li>
            {% empty %}
              <p style="margin: 1em;">没有相关文章！</p>
          {% endfor %}
        </ul>
    </div>
	<section class="comment-area" id="comment-area">
        <hr>
        <h3>发表评论</h3>
        <form action="{% url 'comments:post_comment' post.pk %}" method="post" class="comment-form">
            {% csrf_token %}
            <div class="row">
                <div class="col-md-4">
                    <label for="{{ form.name.id_for_label }}">名字：</label>
                    {{ form.name }}
                    {{ form.name.errors }}
                </div>
                <div class="col-md-4">
                    <label for="{{ form.email.id_for_label }}">邮箱：</label>
                    {{ form.email }}
                    {{ form.email.errors }}
                </div>
                <div class="col-md-4">
                    <label for="{{ form.url.id_for_label }}">URL：</label>
                    {{ form.url }}
                    {{ form.url.errors }}
                </div>
                <div class="col-md-12">
                    <label for="{{ form.text.id_for_label }}">评论：</label>
                    {{ form.text }}
                    {{ form.text.errors }}
                    <button type="submit" class="comment-btn">发表</button>
                </div>
            </div>    
			<!-- row -->
        </form>
        <div class="comment-list-panel">
            <h3>评论列表，共 <span>{{ post.comment_set.count }}</span> 条评论</h3>
            <ul class="comment-list list-unstyled">
                {% for comment in comment_list %}
                    <li class="comment-item">
                        <span class="nickname">{{ comment.name }}</span>
                        <time class="submit-date"
                              datetime="{{ comment.created_time }}">{{ comment.created_time }}</time>
                        <div class="text">
                            {{ comment.text }}
                        </div>
                    </li>
                {% empty %}
                    暂无评论
                {% endfor %}
            </ul>
        </div>
    </section>
	
    <ul class="pager" id="non-printable">
      <li class="previous">
      {% if object.get_previous_by_created %}
        <a href="{% url 'detail_post_page' slug=object.get_previous_by_created.slug %}">&larr; 后退</a>
      {% endif %}
      </li>
      <li class="next">
      {% if object.get_next_by_created %}
        <a href="{% url 'detail_post_page' slug=object.get_next_by_created.slug %}">前进 &rarr;</a>
      {% endif %}
      </li>
    </ul>

    {% load disqus_tags %}
    {% set_disqus_identifier "blogpost_" object.title %}
    {% set_disqus_title object.title %}
    {% disqus_show_comments %}
    <!-- disqus_dev -->
  </div>
  <link rel="stylesheet" href="{% static 'assets/css/highlight.css' %}">
  <script src="//cdnjs.cloudflare.com/ajax/libs/highlight.js/9.5.0/highlight.min.js"></script>
  <script type="text/javascript">
    $(document).ready(function() {
      $('pre').each(function(i, block) {
        hljs.highlightBlock(block);
      });
    });
  </script>
{% endblock %}

blog/templates/blog/blog_home.html
{% extends "base.html" %}
{% load staticfiles %}

{% block content %}
  {% block message_info_homepage %}{% endblock %}

  {% for object in object_list %}
    <div class="post">
      <h2><a href="{% url 'detail_post_page' slug=object.slug %}">{{ object.title }}</a></h2>
      <p class="meta">
        通过: <a href="{% url 'author_posts_page' username=object.author.user.username %}" style="text-transform:uppercase">{{ object.author }}</a> &#9679;
        在 {{ object.created }} &#9679;
        发表：
        {% for tag in object.tags.all %}
          <a href="{% url 'tag_posts_page' slug=tag.slug %}">#{{ tag }}</a>{% if not forloop.last %}, {% endif %}
        {% empty %}Uncategories
        {% endfor %}
      </p>

      {% if object.cover %}
        <div class="cst__cover__posts">
          <a href="{% url 'detail_post_page' slug=object.slug %}">
            <img style="width:100%" src="/media/{{ object.cover }}" alt="{{ object.title }}" title="{{ object.title }}">
          </a>
        </div>
      {% endif %}
      {{ object.description|safe|striptags|truncatewords:"50"|linebreaks }}
      <span style="margin-bottom: .5em;float:right">
        <a href="{% url 'detail_post_page' slug=object.slug %}">阅读更多 &rarr;</a>
      </span>
      <div style="clear:both;border-bottom: 1px solid #F2F2F2;margin: 10px 0"></div>
    </div>
  {% empty %}
    <p class="alert alert-warning text-center cst__radus"><span class="glyphicon glyphicon-info-sign"></span> 没有发表！</p>
  {% endfor %}

  {% if is_paginated %}
    {% if request.GET.q %}
      <ul class="pagination">
        <li {% if not page_obj.has_previous %}class="disabled"{% endif %}>
          <a {% if page_obj.has_previous %}href="?q={{ query }}&amp;page={{ page_obj.previous_page_number }}" aria-label="Previous" {% endif %}><span aria-hidden="true">&laquo;</span></a>
        </li>
        <li><a href="?q={{ query }}&amp;page=1">首页</a></li>
        {% for linkpage in page_range %}
        {% ifequal linkpage page_obj.number %}
        <li class="active">
          <a>{{ page_obj.number }}<span class="sr-only">(当前页)</span></a>
        </li>
        {% else %}
        <li><a href="?q={{ query }}&amp;page={{ linkpage }}">{{ linkpage }}</a></li>
        {% endifequal %}
        {% endfor %}
        <li><a href="?q={{ query }}&amp;page={{ page_obj.paginator.num_pages }}">尾页</a></li>
        <li {% if not page_obj.has_next %}class="disabled"{% endif %}>
          <a {% if page_obj.has_next %}href="?q={{ query }}&amp;page={{ page_obj.next_page_number }}" aria-label="Next" {% endif %}><span aria-hidden="true">&raquo;</span></a>
        </li>
      </ul>
    {% else %}
      <ul class="pagination">
        <li {% if not page_obj.has_previous %}class="disabled"{% endif %}>
          <a {% if page_obj.has_previous %}href="?page={{ page_obj.previous_page_number }}" aria-label="Previous" {% endif %}><span aria-hidden="true">&laquo;</span></a>
        </li>
        <li><a href="?page=1">首页</a></li>
        {% for linkpage in page_range %}
        {% ifequal linkpage page_obj.number %}
        <li class="active">
          <a>{{ page_obj.number }}<span class="sr-only">(当前页)</span></a>
        </li>
        {% else %}
        <li><a href="?page={{ linkpage }}">{{ linkpage }}</a></li>
        {% endifequal %}
        {% endfor %}
        <li><a href="?page={{ page_obj.paginator.num_pages }}">尾页</a></li>
        <li {% if not page_obj.has_next %}class="disabled"{% endif %}>
          <a {% if page_obj.has_next %}href="?page={{ page_obj.next_page_number }}" aria-label="Next" {% endif %}><span aria-hidden="true">&raquo;</span></a>
        </li>
      </ul>
    {% endif %}{# endif request.GET.q #}
  {% endif %}
{% endblock %}

blog/templates/blog/blog_page.html
{% extends "base.html" %}
{% block title %}{{ object.title }} - {{ block.super }}{% endblock %}
{% block canonical_url %}https://{{ request.get_host }}{% url 'detail_page' slug=object.slug %}{% endblock %}

{% block meta_seo %}
  <meta name="description" content="{{ object.description|safe|striptags|truncatewords:"20" }}">
  <meta name="author" content="{{ object.author }}">
  <meta name="keywords" content="{{ object.title }}"/>
  <meta property="og:locale" content="en_US" />
  <meta property="og:type" content="article" />
  <meta property="og:title" content="{{ object.title }}"/>
  <meta property="og:description" content="{{ object.description|safe|striptags|truncatewords:"20" }}"/>
  <meta property="og:url" content="https://{{ request.get_host }}{% url 'detail_page' slug=object.slug %}"/>
  <meta property="og:site_name" content="python.web.id" />
  <meta name="twitter:card" content="summary"/>
  <meta name="twitter:description" content="{{ object.description|safe|striptags|truncatewords:"20" }}"/>
  <meta name="twitter:title" content="{{ object.title }}"/>
  <meta name="twitter:domain" content="python.web.id"/>
  <meta name="twitter:creator" content="@agusmakmun6"/>
{% endblock %}

{% block content %}
  <div class="post post__page" id="printable">
    <h2><a href="{% url "detail_page" slug=object.slug %}">{{ object.title }}</a></h2>
    <p class="meta">
      创建: {{ object.created }} - 修改: {{ object.modified }} - 
      通过: <a href="{% url 'author_posts_page' username=object.author.user.username %}">{{ object.author }}</a>
    </p>
    {{ object.description|safe }}
  </div>
{% endblock %}